---
kind: pipeline
name: documentation

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  image: plugins/gh-pages:latest
  settings:
    pages_directory: _docs/
    password:
      from_secret: github_token
    target_branch: docs
    username:
      from_secret: github_username

- name: trigger
  image: plugins/downstream
  settings:
    fork: true
    repositories:
    - owncloud-ansible/owncloud-ansible.github.io@source
    server: https://drone.owncloud.com
    token:
      from_secret: drone_token

trigger:
  ref:
  - refs/heads/master

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack:1
  settings:
    channel:
      from_secret: slack_channel
    webhook:
      from_secret: slack_webhook_private

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- documentation

---
kind: signature
hmac: 443714ef977207ac10f0b7587028390412c99ecae83a131732d641078dcd7715

...
