---
owncloud_version: "10.6.0"
owncloud_fqdn: ubuntu.owncloud.demo

# If you would like to access your ownCloud by IP
# you can add it to trusted domains.
owncloud_trusted_domains:
  - "{{ owncloud_fqdn }}"
  - "{{ ansible_default_ipv4.address }}"

# You can also adjust the default ownCloud user.
# For security reasons you should set a strong password!
owncloud_admin_username: admin
owncloud_admin_password: owncloud

owncloud_db_name: owncloud
owncloud_db_user: owncloud
owncloud_db_password: owncloud

owncloud_web_default_language: "de_DE"

owncloud_deploy_path: /var/www/owncloud
owncloud_src_path: "/usr/local/src/{{ owncloud_system_user }}"
owncloud_data_path: "{{ owncloud_src_path }}/data"
owncloud_config_path: "{{ owncloud_src_path }}/config"

owncloud_apps:
  - name: activity
  - name: contacts
  - name: twofactor_totp
  - name: files_mediaviewer
  - name: password_policy
  - name: brute_force_protection

# Only supported for ownCloud >= 10.2.1
owncloud_encryption_enabled: True
owncloud_encryption_force_encrypt_all: False

owncloud_log_timezone: "Etc/UTC"
owncloud_log_dateformat: "Y-m-d H:i:s.u"

php_default_version: "7.3"
php_date_timezone: "{{ owncloud_log_timezone }}"
php_packages_extra:
  - gcc
  - make

apache_packages_extra: []

apache_vhosts:
  - servername: "{{ owncloud_fqdn }}"
    documentroot: "{{ owncloud_deploy_path }}"
...
